#!/bin/bash
echo "Generating javadoc"
javadoc -d docs \
        -cp ".:lib/apiguardian-api-1.1.2.jar:lib/junit-jupiter-5.9.2.jar:lib/junit-jupiter-api-5.9.2.jar:lib/junit-jupiter-engine-5.9.2.jar:lib/junit-jupiter-params-5.9.2.jar:lib/junit-platform-commons-1.9.2.jar:lib/junit-platform-engine-1.9.2.jar:lib/opentest4j-1.2.0.jar" \
        src/*/*
echo "Finished"
